# Generated by Django 4.2.7 on 2025-11-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this event', null=True, upload_to='events/'),
        ),
    ]
