# Generated by Django 4.2.7 on 2025-11-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.CharField(blank=True, help_text='Topic or theme for this event', max_length=200, null=True),
        ),
    ]
