# Generated by Django 4.2.7 on 2025-11-27 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in_method', models.CharField(choices=[('qr', 'QR Code'), ('manual', 'Manual Search'), ('admin', 'Admin Entry')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_records', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='people.person')),
            ],
            options={
                'ordering': ['-check_in_time'],
                'unique_together': {('person', 'event')},
            },
        ),
    ]
