# Generated by Django 4.2.7 on 2025-11-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='external_id',
            field=models.CharField(blank=True, help_text='External message ID from API', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='variables',
            field=models.CharField(blank=True, help_text='Available variables: {name}, {event_name}, {event_date}, {event_time}, {event_location}, {event_topic}', max_length=500),
        ),
    ]
