# Generated by Django 4.2.7 on 2025-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notification_preference',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('both', 'Both'), ('none', 'None')], default='whatsapp', help_text='Preferred method for event reminders and notifications', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(help_text='International format: +1234567890', max_length=20, unique=True),
        ),
    ]
